# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0dbc46640d562939b0fbe1805a72007430233c3b73e65db65aca600d8598382a0cab00773f2a124aee1ee2c3532765175484bbc803525ec1eb97237947f9e11

test:
  secret_key_base: b1301d063a038ee7e54c287c78e14fde38d53ca8d02b31d99251fccb87021e06558fcc34d8493879de5b61f95ea2670076c5186cff4dcab83e14dca2d37b3925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
